version: '2'

services:

  web:
    image: slidewiki/nlpstore:latest-dev
    restart: on-failure:5
    expose:
      - 80
    external_links:
      - mongodb
      - solr
    environment:
      - APPLICATION_PORT=80
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - VIRTUAL_HOST=nlpstore.experimental.slidewiki.org
      - LETSENCRYPT_HOST=nlpstore.experimental.slidewiki.org
      - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
      - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
      - SERVICE_URL_NLP=https://nlpservice.experimental.slidewiki.org
      - AGENDA_JOBS_COLLECTION=agendaJobs
      - AGENDA_JOBS_CONCURRENCY=1
    network_mode: bridge

  indexer:
    image: slidewiki/nlpstore:latest-dev
    command: 'node worker'
    restart: on-failure:5
    external_links:
      - mongodb
      - solr
    environment:
      - DATABASE_PORT=27017
      - DATABASE_URL=mongodb
      - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
      - SERVICE_URL_NLP=https://nlpservice.experimental.slidewiki.org
      - AGENDA_JOBS_COLLECTION=agendaJobs
      - AGENDA_JOBS_CONCURRENCY=1
      - JOB_TYPES=nlpUpdate
    network_mode: bridge
