nlpstore:
  image: slidewiki/nlpstore
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file
    - VIRTUAL_HOST=nlpstore.experimental.slidewiki.org
    - LETSENCRYPT_HOST=nlpstore.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
    - SERVICE_URL_DISCUSSION=https://discussionservice.experimental.slidewiki.org
    - SERVICE_URL_ACTIVITIES=https://activitiesservice.experimental.slidewiki.org
    - SERVICE_URL_NOTIFICATION=https://notificationservice.experimental.slidewiki.org
    - SERVICE_URL_USER=https://userservice.experimental.slidewiki.org
    - SERVICE_URL_SEARCH=https://searchservice.experimental.slidewiki.org
    - SERVICE_URL_IMAGE=https://imageservice.experimental.slidewiki.org
    - SERVICE_URL_FILE=https://fileservice.experimental.slidewiki.org
    - SERVICE_URL_PDF=https://pdfservice.experimental.slidewiki.org
    - SERVICE_URL_IMPORT=https://importservice.experimental.slidewiki.org
    - SERVICE_URL_NLP=https://nlpservice.experimental.slidewiki.org
