nlpstore:
  image: slidewiki/nlpstore:latest-dev
  restart: on-failure:5
  expose:
    - "80"
  external_links:
    - mongodb
  environment:
    - APPLICATION_PORT=80
    - DATABASE_PORT=27017
    - DATABASE_URL=mongodb # use a url or the name, defined in the docker-compose file
    - VIRTUAL_HOST=nlpstore.experimental.slidewiki.org
    - LETSENCRYPT_HOST=nlpstore.experimental.slidewiki.org
    - LETSENCRYPT_EMAIL=meissner@informatik.uni-leipzig.de
    - SERVICE_URL_DECK=https://deckservice.experimental.slidewiki.org
    - SERVICE_URL_NLP=https://nlpservice.experimental.slidewiki.org
    - SOLR_HOST=solr.experimental.slidewiki.org